KERNELDIR := /home/zhaoxigang/git/linux-imx
CURRENT_PATH := $(shell pwd)

obj-m := inputkey.o

build: kernel_modules

kernel_modules:
	$(MAKE) -C $(KERNELDIR) M=$(CURRENT_PATH) modules

clean:
	$(MAKE) -C $(KERNELDIR) M=$(CURRENT_PATH) clean